# Generated by Django 5.2.6 on 2025-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=64)),
                ('pr_desc', models.TextField()),
                ('pr_img', models.ImageField(upload_to='media/')),
                ('pr_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
