# Generated by Django 5.2.6 on 2025-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
