# Generated by Django 5.2.6 on 2025-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_siteapp', '0002_project_pr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pr_img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
