# Generated by Django 5.2.6 on 2025-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_siteapp', '0003_alter_project_pr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pr_stech',
            field=models.TextField(null=True),
        ),
    ]
